services:

  paprika-pg:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  paprika-app:
    build: ./backend
    expose:
      - 8000
    command: gunicorn paprika.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - paprika-pg

  paprika-nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - paprika-app

volumes:
  postgres_data:
  static_volume:
  media_volume:
