services:

  paprika-pg:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

  paprika-app:
    build: ./backend
    expose:
      - 8000
    command: gunicorn paprika.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - paprika-pg
    restart: unless-stopped

  paprika-nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - paprika-app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
