services:

  paprika-pg:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  paprika-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    depends_on:
      - paprika-pg

volumes:
  postgres_data:
  media_volume:
