services:

  paprika-pg:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev

  paprika-redis:
    image: redis:alpine
    # restart: always
    ports:
      - "6379:6379"

  paprika-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    depends_on:
      - paprika-pg
      - paprika-redis

  paprika-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - paprika-app

volumes:
  postgres_data:
  media_volume:
