FROM python:3.13-alpine

RUN apk add ffmpeg

RUN adduser -D paprika
USER paprika

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./
RUN pip install -r requirements.txt -r requirements-dev.txt
COPY . /app/
