FROM python:3.13-alpine

RUN adduser -D paprika
USER paprika

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/

RUN mkdir ./media
