# Generated by Django 5.0.8 on 2024-08-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_status_task_shottask_shot_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="shot",
            name="pixel_aspect",
            field=models.FloatField(default=1.0, verbose_name="Аспект пикселя"),
        ),
        migrations.AddField(
            model_name="shot",
            name="rec_timecode",
            field=models.CharField(
                blank=True,
                help_text="Задается в виде 00:00:00:00",
                max_length=11,
                verbose_name="Начальный таймкод в монтаже",
            ),
        ),
        migrations.AddField(
            model_name="shot",
            name="retime_speed",
            field=models.FloatField(
                default=100,
                help_text="100% - скорость без изменений, 200% - в 2 раза быстрее, 50% - в 2 раза медленнее",
                verbose_name="скорость ретайма",
            ),
        ),
        migrations.AddField(
            model_name="shot",
            name="scene",
            field=models.IntegerField(blank=True, null=True, verbose_name="Номер сцены"),
        ),
        migrations.AddField(
            model_name="shot",
            name="source_end_timecode",
            field=models.CharField(
                blank=True,
                help_text="Задается в виде 00:00:00:00",
                max_length=11,
                verbose_name="Конечный таймкод по исходнику",
            ),
        ),
        migrations.AddField(
            model_name="shot",
            name="source_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="имя исходника"),
        ),
        migrations.AddField(
            model_name="shot",
            name="source_start_timecode",
            field=models.CharField(
                blank=True,
                help_text="Задается в виде 00:00:00:00",
                max_length=11,
                verbose_name="Начальный таймкод по исходнику",
            ),
        ),
    ]
