# Generated by Django 5.0.8 on 2024-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_shot_pixel_aspect_shot_rec_timecode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="scene",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер сцены"
            ),
        ),
    ]
