# Generated by Django 5.0.8 on 2024-08-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_shot_scene"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="scene",
            field=models.CharField(
                blank=True, default="", max_length=15, verbose_name="Номер сцены"
            ),
            preserve_default=False,
        ),
    ]
