# Generated by Django 5.0.8 on 2024-08-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_shot_scene"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shot",
            name="group",
        ),
        migrations.AddField(
            model_name="shot",
            name="group",
            field=models.ManyToManyField(
                related_name="shots",
                to="core.shotgroup",
                verbose_name="группа, которой принадлежит шот",
            ),
        ),
    ]
