# Generated by Django 5.0.8 on 2024-08-26 08:36

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_shot_group_shot_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmpShotPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.FileField(upload_to=core.models.shot_preview_upload_path)),
                (
                    "shot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tmp_preview",
                        to="core.shot",
                    ),
                ),
            ],
        ),
    ]
