# Generated by Django 5.0.8 on 2024-08-31 10:01

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_task_default_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="color",
            field=colorfield.fields.ColorField(
                default="#ffffff",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="цвет метки",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="default_status",
            field=models.ForeignKey(
                blank=True,
                help_text="Будет установлен при добавлении задачи в шот. Prepopulated_fields здесь не работает, нужна самописная вьюха",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.status",
                verbose_name="статус по умолчанию",
            ),
        ),
    ]
