# Generated by Django 5.0.8 on 2024-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_status_color_alter_task_default_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shot",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
