# Generated by Django 5.0.8 on 2024-09-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_shot_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кем создан",
            ),
        ),
        migrations.AlterField(
            model_name="shot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_shots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кем создан",
            ),
        ),
        migrations.AlterField(
            model_name="shotgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_shot_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кем создан",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_statuses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кем создан",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кем создана",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
