# Generated by Django 5.0.8 on 2024-09-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_project_created_by_alter_shot_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shot",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shots",
                to="core.project",
                verbose_name="проект",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.project",
                verbose_name="проект",
            ),
        ),
    ]
