# Generated by Django 5.1.5 on 2025-01-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_version_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'get_latest_by': 'created_at'},
        ),
    ]
