# Generated by Django 5.1.5 on 2025-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_version_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название версии'),
        ),
    ]
