# Generated by Django 5.1.8 on 2025-05-06 06:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_version_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='video',
            field=models.FileField(null=True, upload_to=core.models.version_upload_path),
        ),
    ]
