# Generated by Django 5.1.9 on 2025-05-18 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_version_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_shot_name_per_project'),
        ),
    ]
