# Generated by Django 5.2.1 on 2025-06-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shot_unique_shot_name_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotgroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shotgroup',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
