# Generated by Django 5.2.1 on 2025-06-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_shotgroup_is_default_shotgroup_is_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotgroup',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Дефолтная?'),
        ),
        migrations.AlterField(
            model_name='shotgroup',
            name='is_root',
            field=models.BooleanField(default=False, verbose_name='Корневая?'),
        ),
    ]
