# Generated by Django 5.2.1 on 2025-06-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_shotgroup_is_default_alter_shotgroup_is_root'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shottask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='назначено'),
        ),
        migrations.AddField(
            model_name='shottask',
            name='hours',
            field=models.FloatField(blank=True, null=True, verbose_name='часы'),
        ),
    ]
