# Generated by Django 5.2.3 on 2025-06-19 19:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.project_thumb_upload_path),
        ),
    ]
