# Generated by Django 5.2.6 on 2025-09-04 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_project_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shottask',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_tasks', to='core.shot', verbose_name='шот'),
        ),
        migrations.AlterField(
            model_name='shottask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_tasks', to='core.task', verbose_name='задача'),
        ),
    ]
