# Generated by Django 5.2.6 on 2025-09-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_shottask_shot_alter_shottask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='comment',
        ),
        migrations.DeleteModel(
            name='TmpShotPreview',
        ),
    ]
