# Generated by Django 5.2.8 on 2025-11-07 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_shot_comment_delete_tmpshotpreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shotgroup',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_group_name_per_project'),
        ),
    ]
